version: "3.8"
services:
  orders:
    build: .
    container_name: orders-api
    ports: ["8080:8080"]
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - JAVA_OPTS=-Dmanagement.metrics.export.datadog.apiKey=${DD_API_KEY}
    depends_on:
      - datadog

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - DD_SITE=us5.datadoghq.com   # use your site (e.g., datadoghq.com, datadoghq.eu, us3, us5)
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
    ports: ["8125:8125/udp"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
